#!/bin/bash

set -e

case "$1" in
    remove)
        which update-grub > /dev/null 2>&1
        if [ $? -ne 0 ]; then
            echo "Cannot update Grub because update-grub is not installed."
            exit 1
        fi
        update-grub
    ;;

    purge|failed-upgrade|upgrade)
    ;;

    *)
        echo "$DPKG_MAINTSCRIPT_NAME called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
